import bcrypt from 'bcryptjs';

const data = {
  // products: [
  //   {
  //     name: 'Polo Shirt',
  //     category: 'Shirts',
  //     image: '/images/shirt1.jpg',
  //     price: 30,
  //     brand: 'Titlest',
  //     rating: 4.5,
  //     numReviews: 10,
  //     countInStock: 20,
  //     description: 'A popular shirt',
  //     slug: 'polo-shirt',
  //   },
  //   {
  //     name: 'T-Shirt',
  //     category: 'Shirts',
  //     image: '/images/shirt2.jpg',
  //     price: 20,
  //     brand: 'Nike',
  //     rating: 4.0,
  //     numReviews: 12,
  //     countInStock: 20,
  //     description: 'A popular shirt',
  //     slug: 't-shirt',
  //   },
  //   {
  //     name: 'Slim Shirt',
  //     category: 'Shirts',
  //     image: '/images/shirt3.jpg',
  //     price: 22,
  //     brand: 'Adidas',
  //     rating: 2.5,
  //     numReviews: 8,
  //     countInStock: 10,
  //     description: 'A popular shirt',
  //     slug: 'slim-shirt',
  //   },
  //   {
  //     name: 'Golf Pants',
  //     category: 'Pants',
  //     image: '/images/pants1.jpg',
  //     price: 35,
  //     brand: 'Titlest',
  //     rating: 4.5,
  //     numReviews: 5,
  //     countInStock: 20,
  //     description: 'A popular pair of pants',
  //     slug: 'golf-pants',
  //   },
  //   {
  //     name: 'Skinny Shirt',
  //     category: 'Pants',
  //     image: '/images/pants2.jpg',
  //     price: 40,
  //     brand: 'Nike',
  //     rating: 4.5,
  //     numReviews: 10,
  //     countInStock: 20,
  //     description: 'Smart looking pants',
  //     slug: 'slim-shirt',
  //   },
  //   {
  //     name: 'Khaki Pants',
  //     category: 'Pants',
  //     image: '/images/pants3.jpg',
  //     price: 60,
  //     brand: 'Dickies',
  //     rating: 4.7,
  //     numReviews: 7,
  //     countInStock: 5,
  //     description: 'A nice pair of khaki pants',
  //     slug: 'khaki-pants',
  //   },
  // ],
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('password'),
      isAdmin: true,
    },
    {
      name: 'Sarah',
      email: 'sarah@example.com',
      password: bcrypt.hashSync('password'),
      isAdmin: false,
    },
  ],
};

export default data;
